-- MySQL Script generated by MySQL Workbench
-- Mon Oct 11 10:10:34 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bingo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bingo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bingo` DEFAULT CHARACTER SET utf8 ;
USE `bingo` ;

-- -----------------------------------------------------
-- Table `bingo`.`jogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bingo`.`jogo` (
  `id_jogo` INT NOT NULL AUTO_INCREMENT,
  `qtd_cartela_jogo` INT NULL,
  `valor_cartela_jogo` FLOAT NULL,
  `porcentagem_casa` FLOAT NULL,
  PRIMARY KEY (`id_jogo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bingo`.`cartela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bingo`.`cartela` (
  `id_cartela` INT NOT NULL AUTO_INCREMENT,
  `img_codigo_barra` VARCHAR(255) NULL,
  `n_codigo_barra` VARCHAR(150) NULL,
  PRIMARY KEY (`id_cartela`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bingo`.`jogo_cartela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bingo`.`jogo_cartela` (
  `jogo_id_jogo` INT NOT NULL,
  `cartela_id_cartela` INT NOT NULL,
  PRIMARY KEY (`jogo_id_jogo`, `cartela_id_cartela`),
  INDEX `fk_jogo_has_cartela_cartela1_idx` (`cartela_id_cartela` ASC) ,
  INDEX `fk_jogo_has_cartela_jogo_idx` (`jogo_id_jogo` ASC) ,
  CONSTRAINT `fk_jogo_has_cartela_jogo`
    FOREIGN KEY (`jogo_id_jogo`)
    REFERENCES `bingo`.`jogo` (`id_jogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogo_has_cartela_cartela1`
    FOREIGN KEY (`cartela_id_cartela`)
    REFERENCES `bingo`.`cartela` (`id_cartela`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
